language: php

php:
    - 7.0
    - 7.1
    - hhvm

sudo: false

env:
  - PHPUNIT_VERSION="@stable"

matrix:
  include:
    - php: 7.0
      env: PHPUNIT_VERSION="6.0.*"
    - php: 7.0
      env: PHPUNIT_VERSION="dev-master"
    - php: 7.1
      env: PHPUNIT_VERSION="6.0.*"
    - php: 7.1
      env: PHPUNIT_VERSION="dev-master"
  allow_failures:
    - php: hhvm
    - env: PHPUNIT_VERSION="dev-master"

before_script:
    - composer require phpunit/phpunit:${PHPUNIT_VERSION} -n --prefer-source
    - mkdir -p build/logs

script:
    - bin/phpunit --coverage-clover build/logs/clover.cov

after_script:
    - bin/ocular code-coverage:upload --format=php-clover build/logs/clover.cov
