language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

env:
  - PHPUNIT_VERSION="@stable"

matrix:
  include:
    - php: 5.6
      env: PHPUNIT_VERSION="3.7.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.0.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.1.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.2.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.3.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.4.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.5.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.6.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.8.*"
    - php: 5.6
      env: PHPUNIT_VERSION="5.0.*"
    - php: 5.6
      env: PHPUNIT_VERSION="4.8.x-dev"
    - php: 5.6
      env: PHPUNIT_VERSION="5.0.x-dev"
    - php: 5.6
      env: PHPUNIT_VERSION="5.1.x-dev"
    - php: 5.6
      env: PHPUNIT_VERSION="5.2.x-dev"
    - php: 7.0
      env: PHPUNIT_VERSION="6.0.x-dev"
    - php: 7.0
      env: PHPUNIT_VERSION="dev-master"
  allow_failures:
    - php: 7.0
    - php: hhvm
    - env: PHPUNIT_VERSION="4.8.x-dev"
    - env: PHPUNIT_VERSION="5.0.x-dev"
    - env: PHPUNIT_VERSION="5.1.x-dev"
    - env: PHPUNIT_VERSION="5.2.x-dev"
    - env: PHPUNIT_VERSION="6.0.x-dev"
    - env: PHPUNIT_VERSION="dev-master"

before_script:
    - composer require phpunit/phpunit:${PHPUNIT_VERSION} -n --prefer-source
    - mkdir -p build/logs

script:
    - bin/phpunit --coverage-clover build/logs/clover.cov

after_script:
    - bin/ocular code-coverage:upload --format=php-clover build/logs/clover.cov
